spring:
   profiles:
      active:
         - cat
         - PT
         - prod
di:
   username: ymlsuperuser
   password: ymldbpassword
   jdbcurl: ymljdbcurltest

---
spring:
   profiles: prod   
di:
   username: prodsuperuser
   password: proddbpassword
   jdbcurl: proddbcurltest