CREATE TABLE PROJECT (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL
);

CREATE TABLE VERSION (
    ID VARCHAR(36) PRIMARY KEY,
    VERSION NUMERIC(10, 20) NOT NULL,
    PROJECT_ID VARCHAR(36) NOT NULL REFERENCES PROJECT(ID)
);

CREATE TABLE PROJECT_PARAMETER(
    ID VARCHAR(36) PRIMARY KEY,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(256) NOT NULL,
    PROJECT_ID VARCHAR(256) NOT NULL REFERENCES PROJECT(ID)
);
